export const COUNTRIES = [
    { name: "Afghanistan", code: "+93", iso: "AF", min: 9, max: 9 },
    { name: "Albania", code: "+355", iso: "AL", min: 3, max: 9 },
    { name: "Algeria", code: "+213", iso: "DZ", min: 8, max: 9 },
    { name: "American Samoa", code: "+1684", iso: "AS", min: 7, max: 7 },
    { name: "Andorra", code: "+376", iso: "AD", min: 6, max: 9 },
    { name: "Angola", code: "+244", iso: "AO", min: 9, max: 9 },
    { name: "Anguilla", code: "+1264", iso: "AI", min: 7, max: 7 },
    { name: "Antigua and Barbuda", code: "+1268", iso: "AG", min: 7, max: 7 },
    { name: "Argentina", code: "+54", iso: "AR", min: 10, max: 10 },
    { name: "Armenia", code: "+374", iso: "AM", min: 8, max: 8 },
    { name: "Aruba", code: "+297", iso: "AW", min: 7, max: 7 },
    { name: "Australia", code: "+61", iso: "AU", min: 5, max: 15 },
    { name: "Austria", code: "+43", iso: "AT", min: 4, max: 13 },
    { name: "Azerbaijan", code: "+994", iso: "AZ", min: 8, max: 9 },
    { name: "Bahamas", code: "+1242", iso: "BS", min: 7, max: 7 },
    { name: "Bahrain", code: "+973", iso: "BH", min: 8, max: 8 },
    { name: "Bangladesh", code: "+880", iso: "BD", min: 6, max: 10 },
    { name: "Barbados", code: "+1246", iso: "BB", min: 7, max: 7 },
    { name: "Belarus", code: "+375", iso: "BY", min: 9, max: 10 },
    { name: "Belgium", code: "+32", iso: "BE", min: 8, max: 9 },
    { name: "Belize", code: "+501", iso: "BZ", min: 7, max: 7 },
    { name: "Benin", code: "+229", iso: "BJ", min: 8, max: 8 },
    { name: "Bermuda", code: "+1441", iso: "BM", min: 7, max: 7 },
    { name: "Bhutan", code: "+975", iso: "BT", min: 7, max: 8 },
    { name: "Bolivia", code: "+591", iso: "BO", min: 8, max: 8 },
    { name: "Bosnia and Herzegovina", code: "+387", iso: "BA", min: 8, max: 8 },
    { name: "Botswana", code: "+267", iso: "BW", min: 7, max: 8 },
    { name: "Brazil", code: "+55", iso: "BR", min: 10, max: 11 },
    { name: "British Virgin Islands", code: "+1284", iso: "VG", min: 7, max: 7 },
    { name: "Brunei Darussalam", code: "+673", iso: "BN", min: 7, max: 7 },
    { name: "Bulgaria", code: "+359", iso: "BG", min: 7, max: 9 },
    { name: "Burkina Faso", code: "+226", iso: "BF", min: 8, max: 8 },
    { name: "Burundi", code: "+257", iso: "BI", min: 8, max: 8 },
    { name: "Cambodia", code: "+855", iso: "KH", min: 8, max: 9 },
    { name: "Cameroon", code: "+237", iso: "CM", min: 8, max: 8 },
    { name: "Canada", code: "+1", iso: "CA", min: 10, max: 10 },
    { name: "Cape Verde", code: "+238", iso: "CV", min: 7, max: 7 },
    { name: "Cayman Islands", code: "+1345", iso: "KY", min: 7, max: 7 },
    { name: "Central African Rep.", code: "+236", iso: "CF", min: 8, max: 8 },
    { name: "Chad", code: "+235", iso: "TD", min: 8, max: 8 },
    { name: "Chile", code: "+56", iso: "CL", min: 8, max: 9 },
    { name: "China", code: "+86", iso: "CN", min: 5, max: 12 },
    { name: "Colombia", code: "+57", iso: "CO", min: 8, max: 10 },
    { name: "Comoros", code: "+269", iso: "KM", min: 7, max: 7 },
    { name: "Congo", code: "+242", iso: "CG", min: 9, max: 9 },
    { name: "Cook Islands", code: "+682", iso: "CK", min: 5, max: 5 },
    { name: "Costa Rica", code: "+506", iso: "CR", min: 8, max: 8 },
    { name: "Côte d'Ivoire", code: "+225", iso: "CI", min: 8, max: 8 },
    { name: "Croatia", code: "+385", iso: "HR", min: 8, max: 12 },
    { name: "Cuba", code: "+53", iso: "CU", min: 6, max: 8 },
    { name: "Cyprus", code: "+357", iso: "CY", min: 8, max: 11 },
    { name: "Czech Rep.", code: "+420", iso: "CZ", min: 4, max: 12 },
    { name: "Denmark", code: "+45", iso: "DK", min: 8, max: 8 },
    { name: "Djibouti", code: "+253", iso: "DJ", min: 6, max: 6 },
    { name: "Dominica", code: "+1767", iso: "DM", min: 7, max: 7 },
    { name: "Dominican Rep.", code: "+1809", iso: "DO", min: 7, max: 7 },
    { name: "Ecuador", code: "+593", iso: "EC", min: 8, max: 8 },
    { name: "Egypt", code: "+20", iso: "EG", min: 7, max: 9 },
    { name: "El Salvador", code: "+503", iso: "SV", min: 7, max: 11 },
    { name: "Equatorial Guinea", code: "+240", iso: "GQ", min: 9, max: 9 },
    { name: "Eritrea", code: "+291", iso: "ER", min: 7, max: 7 },
    { name: "Estonia", code: "+372", iso: "EE", min: 7, max: 10 },
    { name: "Ethiopia", code: "+251", iso: "ET", min: 9, max: 9 },
    { name: "Falkland Islands", code: "+500", iso: "FK", min: 5, max: 5 },
    { name: "Faroe Islands", code: "+298", iso: "FO", min: 6, max: 6 },
    { name: "Fiji", code: "+679", iso: "FJ", min: 7, max: 7 },
    { name: "Finland", code: "+358", iso: "FI", min: 5, max: 12 },
    { name: "France", code: "+33", iso: "FR", min: 9, max: 9 },
    { name: "French Guiana", code: "+594", iso: "GF", min: 9, max: 9 },
    { name: "French Polynesia", code: "+689", iso: "PF", min: 6, max: 6 },
    { name: "Gabon", code: "+241", iso: "GA", min: 6, max: 7 },
    { name: "Gambia", code: "+220", iso: "GM", min: 7, max: 7 },
    { name: "Georgia", code: "+995", iso: "GE", min: 9, max: 9 },
    { name: "Germany", code: "+49", iso: "DE", min: 6, max: 13 },
    { name: "Ghana", code: "+233", iso: "GH", min: 5, max: 9 },
    { name: "Gibraltar", code: "+350", iso: "GI", min: 8, max: 8 },
    { name: "Greece", code: "+30", iso: "GR", min: 10, max: 10 },
    { name: "Greenland", code: "+299", iso: "GL", min: 6, max: 6 },
    { name: "Grenada", code: "+1473", iso: "GD", min: 7, max: 7 },
    { name: "Guadeloupe", code: "+590", iso: "GP", min: 9, max: 9 },
    { name: "Guam", code: "+1671", iso: "GU", min: 7, max: 7 },
    { name: "Guatemala", code: "+502", iso: "GT", min: 8, max: 8 },
    { name: "Guinea", code: "+224", iso: "GN", min: 8, max: 8 },
    { name: "Guinea-Bissau", code: "+245", iso: "GW", min: 7, max: 7 },
    { name: "Guyana", code: "+592", iso: "GY", min: 7, max: 7 },
    { name: "Haiti", code: "+509", iso: "HT", min: 8, max: 8 },
    { name: "Honduras", code: "+504", iso: "HN", min: 8, max: 8 },
    { name: "Hong Kong", code: "+852", iso: "HK", min: 8, max: 9 },
    { name: "Hungary", code: "+36", iso: "HU", min: 8, max: 9 },
    { name: "Iceland", code: "+354", iso: "IS", min: 7, max: 9 },
    { name: "India", code: "+91", iso: "IN", min: 10, max: 10 },
    { name: "Indonesia", code: "+62", iso: "ID", min: 5, max: 10 },
    { name: "Iran", code: "+98", iso: "IR", min: 6, max: 10 },
    { name: "Iraq", code: "+964", iso: "IQ", min: 8, max: 10 },
    { name: "Ireland", code: "+353", iso: "IE", min: 7, max: 11 },
    { name: "Israel", code: "+972", iso: "IL", min: 8, max: 9 },
    { name: "Italy", code: "+39", iso: "IT", min: 9, max: 11 },
    { name: "Jamaica", code: "+1876", iso: "JM", min: 7, max: 7 },
    { name: "Japan", code: "+81", iso: "JP", min: 9, max: 10 },
    { name: "Jordan", code: "+962", iso: "JO", min: 5, max: 9 },
    { name: "Kazakhstan", code: "+7", iso: "KZ", min: 10, max: 10 },
    { name: "Kenya", code: "+254", iso: "KE", min: 6, max: 10 },
    { name: "Kiribati", code: "+686", iso: "KI", min: 5, max: 5 },
    { name: "Korea (South)", code: "+82", iso: "KR", min: 8, max: 11 },
    { name: "Kuwait", code: "+965", iso: "KW", min: 7, max: 8 },
    { name: "Kyrgyzstan", code: "+996", iso: "KG", min: 9, max: 9 },
    { name: "Laos", code: "+856", iso: "LA", min: 8, max: 10 },
    { name: "Latvia", code: "+371", iso: "LV", min: 7, max: 8 },
    { name: "Lebanon", code: "+961", iso: "LB", min: 7, max: 8 },
    { name: "Lesotho", code: "+266", iso: "LS", min: 8, max: 8 },
    { name: "Liberia", code: "+231", iso: "LR", min: 7, max: 8 },
    { name: "Libya", code: "+218", iso: "LY", min: 8, max: 9 },
    { name: "Liechtenstein", code: "+423", iso: "LI", min: 7, max: 9 },
    { name: "Lithuania", code: "+370", iso: "LT", min: 8, max: 8 },
    { name: "Luxembourg", code: "+352", iso: "LU", min: 4, max: 11 },
    { name: "Macao", code: "+853", iso: "MO", min: 7, max: 8 },
    { name: "Madagascar", code: "+261", iso: "MG", min: 9, max: 10 },
    { name: "Malawi", code: "+265", iso: "MW", min: 7, max: 8 },
    { name: "Malaysia", code: "+60", iso: "MY", min: 7, max: 9 },
    { name: "Maldives", code: "+960", iso: "MV", min: 7, max: 7 },
    { name: "Mali", code: "+223", iso: "ML", min: 8, max: 8 },
    { name: "Malta", code: "+356", iso: "MT", min: 8, max: 8 },
    { name: "Marshall Islands", code: "+692", iso: "MH", min: 7, max: 7 },
    { name: "Martinique", code: "+596", iso: "MQ", min: 9, max: 9 },
    { name: "Mauritania", code: "+222", iso: "MR", min: 7, max: 7 },
    { name: "Mauritius", code: "+230", iso: "MU", min: 7, max: 7 },
    { name: "Mexico", code: "+52", iso: "MX", min: 10, max: 10 },
    { name: "Micronesia", code: "+691", iso: "FM", min: 7, max: 7 },
    { name: "Moldova", code: "+373", iso: "MD", min: 8, max: 8 },
    { name: "Monaco", code: "+377", iso: "MC", min: 5, max: 9 },
    { name: "Mongolia", code: "+976", iso: "MN", min: 7, max: 8 },
    { name: "Montenegro", code: "+382", iso: "ME", min: 4, max: 12 },
    { name: "Montserrat", code: "+1664", iso: "MS", min: 7, max: 7 },
    { name: "Morocco", code: "+212", iso: "MA", min: 9, max: 9 },
    { name: "Mozambique", code: "+258", iso: "MZ", min: 8, max: 9 },
    { name: "Myanmar", code: "+95", iso: "MM", min: 7, max: 9 },
    { name: "Namibia", code: "+264", iso: "NA", min: 6, max: 10 },
    { name: "Nauru", code: "+674", iso: "NR", min: 4, max: 7 },
    { name: "Nepal", code: "+977", iso: "NP", min: 8, max: 9 },
    { name: "Netherlands", code: "+31", iso: "NL", min: 9, max: 9 },
    { name: "New Caledonia", code: "+687", iso: "NC", min: 6, max: 6 },
    { name: "New Zealand", code: "+64", iso: "NZ", min: 3, max: 10 },
    { name: "Nicaragua", code: "+505", iso: "NI", min: 8, max: 8 },
    { name: "Niger", code: "+227", iso: "NE", min: 8, max: 8 },
    { name: "Nigeria", code: "+234", iso: "NG", min: 7, max: 10 },
    { name: "Niue", code: "+683", iso: "NU", min: 4, max: 4 },
    { name: "Northern Marianas", code: "+1670", iso: "MP", min: 7, max: 7 },
    { name: "Norway", code: "+47", iso: "NO", min: 5, max: 8 },
    { name: "Oman", code: "+968", iso: "OM", min: 7, max: 8 },
    { name: "Pakistan", code: "+92", iso: "PK", min: 8, max: 11 },
    { name: "Palau", code: "+680", iso: "PW", min: 7, max: 7 },
    { name: "Panama", code: "+507", iso: "PA", min: 7, max: 8 },
    { name: "Papua New Guinea", code: "+675", iso: "PG", min: 4, max: 11 },
    { name: "Paraguay", code: "+595", iso: "PY", min: 5, max: 9 },
    { name: "Peru", code: "+51", iso: "PE", min: 8, max: 11 },
    { name: "Philippines", code: "+63", iso: "PH", min: 8, max: 10 },
    { name: "Poland", code: "+48", iso: "PL", min: 6, max: 9 },
    { name: "Portugal", code: "+351", iso: "PT", min: 9, max: 11 },
    { name: "Puerto Rico", code: "+1", iso: "PR", min: 10, max: 10 },
    { name: "Qatar", code: "+974", iso: "QA", min: 3, max: 8 },
    { name: "Romania", code: "+40", iso: "RO", min: 9, max: 9 },
    { name: "Russia", code: "+7", iso: "RU", min: 10, max: 10 },
    { name: "Rwanda", code: "+250", iso: "RW", min: 9, max: 9 },
    { name: "Saint Kitts and Nevis", code: "+1869", iso: "KN", min: 7, max: 7 },
    { name: "Saint Lucia", code: "+1758", iso: "LC", min: 7, max: 7 },
    { name: "Saint Vincent", code: "+1784", iso: "VC", min: 7, max: 7 },
    { name: "Samoa", code: "+685", iso: "WS", min: 3, max: 7 },
    { name: "San Marino", code: "+378", iso: "SM", min: 6, max: 10 },
    { name: "Sao Tome and Principe", code: "+239", iso: "ST", min: 7, max: 7 },
    { name: "Saudi Arabia", code: "+966", iso: "SA", min: 8, max: 9 },
    { name: "Senegal", code: "+221", iso: "SN", min: 9, max: 9 },
    { name: "Serbia", code: "+381", iso: "RS", min: 4, max: 12 },
    { name: "Seychelles", code: "+248", iso: "SC", min: 7, max: 7 },
    { name: "Sierra Leone", code: "+232", iso: "SL", min: 8, max: 8 },
    { name: "Singapore", code: "+65", iso: "SG", min: 8, max: 12 },
    { name: "Sint Maarten", code: "+1721", iso: "SX", min: 7, max: 7 },
    { name: "Slovakia", code: "+421", iso: "SK", min: 4, max: 9 },
    { name: "Slovenia", code: "+386", iso: "SI", min: 8, max: 8 },
    { name: "Solomon Islands", code: "+677", iso: "SB", min: 5, max: 5 },
    { name: "Somalia", code: "+252", iso: "SO", min: 5, max: 8 },
    { name: "South Africa", code: "+27", iso: "ZA", min: 9, max: 9 },
    { name: "South Sudan", code: "+211", iso: "SS", min: 9, max: 9 },
    { name: "Spain", code: "+34", iso: "ES", min: 9, max: 9 },
    { name: "Sri Lanka", code: "+94", iso: "LK", min: 9, max: 9 },
    { name: "Sudan", code: "+249", iso: "SD", min: 9, max: 9 },
    { name: "Suriname", code: "+597", iso: "SR", min: 6, max: 7 },
    { name: "Swaziland", code: "+268", iso: "SZ", min: 7, max: 8 },
    { name: "Sweden", code: "+46", iso: "SE", min: 7, max: 13 },
    { name: "Switzerland", code: "+41", iso: "CH", min: 4, max: 12 },
    { name: "Syria", code: "+963", iso: "SY", min: 8, max: 10 },
    { name: "Taiwan", code: "+886", iso: "TW", min: 8, max: 9 },
    { name: "Tajikistan", code: "+992", iso: "TJ", min: 9, max: 9 },
    { name: "Tanzania", code: "+255", iso: "TZ", min: 9, max: 9 },
    { name: "Thailand", code: "+66", iso: "TH", min: 8, max: 9 },
    { name: "Timor-Leste", code: "+670", iso: "TL", min: 7, max: 7 },
    { name: "Togo", code: "+228", iso: "TG", min: 8, max: 8 },
    { name: "Tokelau", code: "+690", iso: "TK", min: 4, max: 4 },
    { name: "Tonga", code: "+676", iso: "TO", min: 5, max: 7 },
    { name: "Trinidad and Tobago", code: "+1868", iso: "TT", min: 7, max: 7 },
    { name: "Tunisia", code: "+216", iso: "TN", min: 8, max: 8 },
    { name: "Turkey", code: "+90", iso: "TR", min: 10, max: 10 },
    { name: "Turkmenistan", code: "+993", iso: "TM", min: 8, max: 8 },
    { name: "Turks and Caicos", code: "+1649", iso: "TC", min: 7, max: 7 },
    { name: "Tuvalu", code: "+688", iso: "TV", min: 5, max: 6 },
    { name: "Uganda", code: "+256", iso: "UG", min: 9, max: 9 },
    { name: "Ukraine", code: "+380", iso: "UA", min: 9, max: 9 },
    { name: "UAE", code: "+971", iso: "AE", min: 8, max: 9 },
    { name: "UK", code: "+44", iso: "GB", min: 7, max: 10 },
    { name: "USA", code: "+1", iso: "US", min: 10, max: 10 },
    { name: "Uruguay", code: "+598", iso: "UY", min: 4, max: 11 },
    { name: "Uzbekistan", code: "+998", iso: "UZ", min: 9, max: 9 },
    { name: "Vanuatu", code: "+678", iso: "VU", min: 5, max: 7 },
    { name: "Venezuela", code: "+58", iso: "VE", min: 10, max: 10 },
    { name: "Vietnam", code: "+84", iso: "VN", min: 7, max: 10 },
    { name: "Yemen", code: "+967", iso: "YE", min: 6, max: 9 },
    { name: "Zambia", code: "+260", iso: "ZM", min: 9, max: 9 },
    { name: "Zimbabwe", code: "+263", iso: "ZW", min: 5, max: 10 },
];
